table D10_Auditoria
	lineageTag: 0e14fded-5a0a-4ae7-864b-80cee3c543af

	measure 'A10 Eventos' = SUM([Valor])
		formatString: #,0.00
		lineageTag: ed4f5f40-ff37-4513-a49b-5aaf730560e5

	measure 'A10 Eventos OK' = CALCULATE(SUM([Valor]), D10_Auditoria[Estado] = "PASSED" || D10_Auditoria[Estado] = "OK")
		formatString: #,0.00
		lineageTag: 447ad1da-8915-436c-a7b0-ff68ee91e477

	column Fecha
		dataType: string
		lineageTag: 03f70fb9-6356-4738-b756-48611b159c1f
		summarizeBy: none
		sourceColumn: date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 95197a4e-5c67-4c73-8026-c71b98a6c8e7
		summarizeBy: none
		sourceColumn: year

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: 47022230-ab60-4ebc-85dc-689488c067a6
		summarizeBy: none
		sourceColumn: month

	column Servicio
		dataType: string
		lineageTag: 0af0ebf6-0812-44c7-a93f-b82ea3643abb
		summarizeBy: none
		sourceColumn: service

	column Categoría
		dataType: string
		lineageTag: 51fd1628-e475-4fdd-abb0-73c672222b43
		summarizeBy: none
		sourceColumn: category

	column Serie
		dataType: string
		lineageTag: 1f41129a-32a2-47e0-8b71-49dded749dea
		summarizeBy: none
		sourceColumn: series

	column Indicador
		dataType: string
		lineageTag: 508f51cc-5613-4dfc-bc1a-388978b82003
		summarizeBy: none
		sourceColumn: metric_name

	column Valor
		dataType: double
		formatString: #,0.00
		lineageTag: f7cb2ed0-cf01-4e2a-9f4e-dc219b8caa1a
		summarizeBy: sum
		sourceColumn: metric_value

	column 'Valor auxiliar'
		dataType: double
		formatString: #,0.00
		lineageTag: f79e7ff6-1fe7-4be9-aa17-1fd4a944b1dd
		summarizeBy: sum
		sourceColumn: metric_aux

	column Estado
		dataType: string
		lineageTag: 5d8fc193-f503-4113-a7c4-b9321bbf843a
		summarizeBy: none
		sourceColumn: status

	column Detalle
		dataType: string
		lineageTag: d586b818-9825-410a-9bf6-df68fb1814c0
		summarizeBy: none
		sourceColumn: detail

	partition D10_Auditoria = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:/Users/Pieers/dev/bigdata-final/exports/powerbi/D10_Auditoria.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"date", type text}, {"year", Int64.Type}, {"month", Int64.Type}, {"service", type text}, {"category", type text}, {"series", type text}, {"metric_name", type text}, {"metric_value", type number}, {"metric_aux", type number}, {"status", type text}, {"detail", type text}}, "en-US")
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

