table DimCluster
	lineageTag: ebc04ed1-eaf2-43bf-a78b-a58858af1843

	column SegmentoID
		dataType: int64
		lineageTag: a45ba3d3-f935-43a9-b81d-c7934ff5cea2
		summarizeBy: none
		sourceColumn: SegmentoID

	column Segmento
		dataType: string
		lineageTag: e4ab801e-48c8-48f2-a303-6c7624401d53
		summarizeBy: none
		sourceColumn: Segmento

	partition DimCluster = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:/Users/Pieers/dev/bigdata-final/exports/powerbi/dimensions/DimCluster.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Encabezados,{{"SegmentoID", Int64.Type}, {"Segmento", type text}}, "es-ES")
				in
				    Tipos

	annotation PBI_ResultType = Table

