table DimCluster

	column 'SegmentoID'
		dataType: int64
		summarizeBy: none
		sourceColumn: SegmentoID

	column 'Segmento'
		dataType: string
		summarizeBy: none
		sourceColumn: Segmento

	partition DimCluster = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:/Users/Pieers/dev/bigdata-final/exports/powerbi/dimensions/DimCluster.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Encabezados,{{"SegmentoID", Int64.Type}, {"Segmento", type text}}, "es-ES")
				in
				    Tipos

	annotation PBI_ResultType = Table
