table DimFecha

	column 'Fecha'
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Fecha

	column 'Año'
		dataType: int64
		summarizeBy: none
		sourceColumn: Año

	column 'MesNumero'
		dataType: int64
		summarizeBy: none
		sourceColumn: MesNumero

	column 'Mes'
		dataType: string
		summarizeBy: none
		sourceColumn: Mes

	column 'Trimestre'
		dataType: string
		summarizeBy: none
		sourceColumn: Trimestre

	column 'AñoMes'
		dataType: string
		summarizeBy: none
		sourceColumn: AñoMes

	column 'AñoMesOrden'
		dataType: int64
		summarizeBy: none
		sourceColumn: AñoMesOrden

	column 'DiaSemanaNumero'
		dataType: int64
		summarizeBy: none
		sourceColumn: DiaSemanaNumero

	column 'DiaSemana'
		dataType: string
		summarizeBy: none
		sourceColumn: DiaSemana

	column 'EsFinSemana'
		dataType: boolean
		summarizeBy: none
		sourceColumn: EsFinSemana

	partition DimFecha = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:/Users/Pieers/dev/bigdata-final/exports/powerbi/dimensions/DimFecha.csv"),[Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Encabezados,{{"Fecha", type date}, {"Año", Int64.Type}, {"MesNumero", Int64.Type}, {"Mes", type text}, {"Trimestre", type text}, {"AñoMes", type text}, {"AñoMesOrden", Int64.Type}, {"DiaSemanaNumero", Int64.Type}, {"DiaSemana", type text}, {"EsFinSemana", type logical}}, "es-ES")
				in
				    Tipos

	annotation PBI_ResultType = Table
