table DimHora

	column 'Hora'
		dataType: int64
		summarizeBy: none
		sourceColumn: Hora

	column 'FranjaHoraria'
		dataType: string
		summarizeBy: none
		sourceColumn: FranjaHoraria

	column 'Es hora punta'
		dataType: boolean
		summarizeBy: none
		sourceColumn: EsHoraPico

	partition DimHora = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:/Users/Pieers/dev/bigdata-final/exports/powerbi/dimensions/DimHora.csv"),[Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Encabezados,{{"Hora", Int64.Type}, {"FranjaHoraria", type text}, {"EsHoraPico", type logical}}, "es-ES")
				in
				    Tipos

	annotation PBI_ResultType = Table
