table DimPago

	column 'TipoPago'
		dataType: int64
		summarizeBy: none
		sourceColumn: TipoPago

	column 'Forma de pago'
		dataType: string
		summarizeBy: none
		sourceColumn: PagoNombre

	partition DimPago = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:/Users/Pieers/dev/bigdata-final/exports/powerbi/dimensions/DimPago.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Encabezados,{{"TipoPago", Int64.Type}, {"PagoNombre", type text}}, "es-ES")
				in
				    Tipos

	annotation PBI_ResultType = Table
