table DimServicio

	column 'Servicio'
		dataType: string
		summarizeBy: none
		sourceColumn: Servicio

	column 'Nombre del servicio'
		dataType: string
		summarizeBy: none
		sourceColumn: ServicioNombre

	partition DimServicio = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:/Users/Pieers/dev/bigdata-final/exports/powerbi/dimensions/DimServicio.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Encabezados,{{"Servicio", type text}, {"ServicioNombre", type text}}, "es-ES")
				in
				    Tipos

	annotation PBI_ResultType = Table
