table DimServicio
	lineageTag: c66e6b89-e8b7-457b-b29a-03f8d1b14eec

	column Servicio
		dataType: string
		lineageTag: 6bf416fc-142e-45e0-a8f4-f7b5ab480cf3
		summarizeBy: none
		sourceColumn: Servicio

	column 'Nombre del servicio'
		dataType: string
		lineageTag: b41dcea1-daf4-4f52-a2f0-66f5ba6cdf5a
		summarizeBy: none
		sourceColumn: ServicioNombre

	partition DimServicio = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:/Users/Pieers/dev/bigdata-final/exports/powerbi/dimensions/DimServicio.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Encabezados,{{"Servicio", type text}, {"ServicioNombre", type text}}, "es-ES")
				in
				    Tipos

	annotation PBI_ResultType = Table

