table DimZonaDestino

	column 'ID de zona'
		dataType: int64
		summarizeBy: none
		sourceColumn: LocationID

	column 'Distrito'
		dataType: string
		summarizeBy: none
		sourceColumn: Borough

	column 'Zona'
		dataType: string
		summarizeBy: none
		sourceColumn: Zone

	column 'Tipo de zona'
		dataType: string
		summarizeBy: none
		sourceColumn: service_zone

	partition DimZonaDestino = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:/Users/Pieers/dev/bigdata-final/exports/powerbi/dimensions/DimZonaDestino.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Encabezados,{{"LocationID", Int64.Type}, {"Borough", type text}, {"Zone", type text}, {"service_zone", type text}}, "es-ES")
				in
				    Tipos

	annotation PBI_ResultType = Table
