table DimZonaDestino
	lineageTag: ad0ec45b-eb4c-415f-9cf5-326dba071376

	column 'ID de zona'
		dataType: int64
		lineageTag: 9d20d9a0-2d67-41d8-bd6b-74e9aa062936
		summarizeBy: none
		sourceColumn: LocationID

	column Distrito
		dataType: string
		lineageTag: 3e50ce23-409d-4557-a6fa-72427d04bb2f
		summarizeBy: none
		sourceColumn: Borough

	column Zona
		dataType: string
		lineageTag: f884762e-9897-4878-a967-7fa9b5e8a333
		summarizeBy: none
		sourceColumn: Zone

	column 'Tipo de zona'
		dataType: string
		lineageTag: 635b9736-93e8-4ac9-a151-4aefda5b4526
		summarizeBy: none
		sourceColumn: service_zone

	partition DimZonaDestino = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:/Users/Pieers/dev/bigdata-final/exports/powerbi/dimensions/DimZonaDestino.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    Tipos = Table.TransformColumnTypes(Encabezados,{{"LocationID", Int64.Type}, {"Borough", type text}, {"Zone", type text}, {"service_zone", type text}}, "es-ES")
				in
				    Tipos

	annotation PBI_ResultType = Table

