table Fact_ZonasSegmentadas

	measure 'D8 Zonas Segmentadas' = DISTINCTCOUNT(Fact_ZonasSegmentadas[ID zona de origen])
		formatString: #,0
		displayFolder: Medidas

	measure 'D8 Viajes Segmentados' = SUM(Fact_ZonasSegmentadas[Viajes totales])
		formatString: #,0
		displayFolder: Medidas

	measure 'D8 Ingreso por Viaje' = DIVIDE(SUM(Fact_ZonasSegmentadas[Ingresos totales]), SUM(Fact_ZonasSegmentadas[Viajes totales]))
		formatString: $#,0.00
		displayFolder: Medidas

	column 'ID de segmento'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: segment_id

	column 'ID interno de zona'
		dataType: string
		summarizeBy: none
		sourceColumn: zone_id

	column 'Viajes totales'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: total_trips

	column 'Viajes diarios promedio'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_daily_trips

	column 'Variabilidad de la demanda'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: demand_stddev

	column 'Días activos'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: active_days

	column 'Nombre de zona'
		dataType: string
		summarizeBy: none
		sourceColumn: zone_name

	column 'borough'
		dataType: string
		summarizeBy: none
		sourceColumn: borough

	column 'Tarifa promedio'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_fare_amount

	column 'Distancia promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_distance

	column 'Duración promedio en minutos'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_duration_minutes

	column 'Ingresos totales'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: total_revenue

	column 'Perfil del segmento'
		dataType: string
		summarizeBy: none
		sourceColumn: segment_label

	column 'Nivel de demanda'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: demand_rank

	column 'ID zona de origen'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_location_id

	column 'Nombre del modelo'
		dataType: string
		summarizeBy: none
		sourceColumn: model_name

	column 'Fecha de generación UTC'
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: generated_at_utc

	column 'Zona de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_zone

	column 'Distrito de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_borough

	partition Fact_ZonasSegmentadas = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/model_segmentation_zones"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in t),
				    Combinado = Table.Combine(ConDatos[Data])
				in
				    Combinado

	annotation PBI_ResultType = Table
