table Fact_FactoresPropina

	measure 'D6 Tasa Propina Ponderada' = DIVIDE(SUM(Fact_FactoresPropina[Ingresos por propinas]), SUM(Fact_FactoresPropina[Ingresos por tarifa]))
		formatString: 0.00%
		displayFolder: Medidas

	measure 'D6 Viajes con Propina %' = DIVIDE(SUM(Fact_FactoresPropina[Viajes con propina]), SUM(Fact_FactoresPropina[Cantidad de viajes]))
		formatString: 0.00%
		displayFolder: Medidas

	measure 'D6 Viajes Analizados' = SUM(Fact_FactoresPropina[Cantidad de viajes])
		formatString: #,0
		displayFolder: Medidas

	column 'Día de la semana'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_day_of_week

	column 'Hora de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_hour

	column 'Servicio'
		dataType: string
		summarizeBy: none
		sourceColumn: service

	column 'Tipo de pago'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: payment_type

	column 'Distrito de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_borough

	column 'Cantidad de viajes'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: trip_count

	column 'Viajes con propina'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: tipped_trips

	column 'Ingresos por tarifa'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: fare_revenue

	column 'Ingresos por propinas'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tip_revenue

	column 'Tasa promedio de propina por viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_tip_rate

	column 'Distancia promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_distance

	column 'Duración promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_duration_minutes

	column 'Proporción de viajes con propina'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tipped_trip_share

	column 'Tasa agregada de propina'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: aggregate_tip_rate

	column 'Año de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_year

	column 'Mes de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_month

	column 'Mes'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: month_start

	partition Fact_FactoresPropina = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/diagnostic_tip_factors"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in Table.AddColumn(Table.AddColumn(t, "pickup_year", each y, Int64.Type), "pickup_month", each m, Int64.Type)),
				    Combinado = Table.AddColumn(Table.Combine(ConDatos[Data]), "month_start", each try #date([pickup_year], [pickup_month], 1) otherwise null, type date)
				in
				    Combinado

	annotation PBI_ResultType = Table
