table Fact_MetricasSegmentacion

	measure 'D8 Calidad de Segmentos (Silhouette)' = CALCULATE(MAX(Fact_MetricasSegmentacion[Valor de la métrica]), Fact_MetricasSegmentacion[Nombre de la métrica] = "silhouette")
		formatString: 0.0000
		displayFolder: Medidas

	column 'Nombre del modelo'
		dataType: string
		summarizeBy: none
		sourceColumn: model_name

	column 'Nombre de la métrica'
		dataType: string
		summarizeBy: none
		sourceColumn: metric_name

	column 'Valor de la métrica'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: metric_value

	column 'Detalle de la métrica'
		dataType: string
		summarizeBy: none
		sourceColumn: metric_text

	column 'Fecha de generación UTC'
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: generated_at_utc

	partition Fact_MetricasSegmentacion = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/model_segmentation_metrics"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in t),
				    Combinado = Table.Combine(ConDatos[Data])
				in
				    Combinado

	annotation PBI_ResultType = Table
