table Fact_RendimientoRutas

	measure 'D5 Viajes Rutas' = SUM(Fact_RendimientoRutas[Cantidad de viajes])
		formatString: #,0
		displayFolder: Medidas

	measure 'D5 Duracion Ponderada' = DIVIDE(SUMX(Fact_RendimientoRutas, Fact_RendimientoRutas[Duración promedio del viaje] * Fact_RendimientoRutas[Cantidad de viajes]), [D5 Viajes Rutas])
		formatString: 0.00 "min"
		displayFolder: Medidas

	measure 'D5 Velocidad Ponderada' = DIVIDE(SUMX(Fact_RendimientoRutas, Fact_RendimientoRutas[Velocidad promedio en mph] * Fact_RendimientoRutas[Cantidad de viajes]), [D5 Viajes Rutas])
		formatString: 0.00 "mph"
		displayFolder: Medidas

	column 'Servicio'
		dataType: string
		summarizeBy: none
		sourceColumn: service

	column 'ID zona de origen'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_location_id

	column 'Distrito de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_borough

	column 'Zona de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_zone

	column 'ID zona de destino'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: dropoff_location_id

	column 'Distrito de destino'
		dataType: string
		summarizeBy: none
		sourceColumn: dropoff_borough

	column 'Zona de destino'
		dataType: string
		summarizeBy: none
		sourceColumn: dropoff_zone

	column 'Cantidad de viajes'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: trip_count

	column 'Ingresos totales'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: total_revenue

	column 'Distancia promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_distance

	column 'Duración promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_duration_minutes

	column 'Velocidad promedio en mph'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_speed_mph

	column 'Mediana de duración del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: median_trip_duration_minutes

	column 'Tarifa promedio por milla'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_fare_per_mile

	column 'Año de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_year

	column 'Mes de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_month

	column 'Mes'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: month_start

	partition Fact_RendimientoRutas = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/diagnostic_route_performance"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in Table.AddColumn(Table.AddColumn(t, "pickup_year", each y, Int64.Type), "pickup_month", each m, Int64.Type)),
				    Combinado = Table.AddColumn(Table.Combine(ConDatos[Data]), "month_start", each try #date([pickup_year], [pickup_month], 1) otherwise null, type date)
				in
				    Combinado

	annotation PBI_ResultType = Table
