table Fact_FinanzasServicio

	measure 'D3 Ingresos Totales' = SUM(Fact_FinanzasServicio[Ingresos totales])
		formatString: $#,0.00
		displayFolder: Medidas

	measure 'D3 Propinas Totales' = SUM(Fact_FinanzasServicio[Ingresos por propinas])
		formatString: $#,0.00
		displayFolder: Medidas

	measure 'D3 Tasa Propina Ponderada' = DIVIDE(SUM(Fact_FinanzasServicio[Ingresos por propinas]), SUM(Fact_FinanzasServicio[Ingresos por tarifa]))
		formatString: 0.00%
		displayFolder: Medidas

	measure 'D3 Viajes con Propina %' = DIVIDE(SUM(Fact_FinanzasServicio[Viajes con propina]), SUM(Fact_FinanzasServicio[Cantidad de viajes]))
		formatString: 0.00%
		displayFolder: Medidas

	column 'Mes de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_month

	column 'Servicio'
		dataType: string
		summarizeBy: none
		sourceColumn: service

	column 'Tipo de pago'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: payment_type

	column 'Cantidad de viajes'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: trip_count

	column 'Ingresos totales'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: total_revenue

	column 'Ingresos por tarifa'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: fare_revenue

	column 'Ingresos por propinas'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tip_revenue

	column 'Ingresos por peajes'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tolls_revenue

	column 'Impuestos y recargos'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: taxes_and_surcharges

	column 'Importe total promedio'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_total_amount

	column 'Propina promedio'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_tip_amount

	column 'Viajes con propina'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: tipped_trips

	column 'Año de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_year

	column 'Mes'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: month_start

	partition Fact_FinanzasServicio = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/descriptive_service_financials"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in Table.AddColumn(t, "pickup_year", each y, Int64.Type)),
				    Combinado = Table.AddColumn(Table.Combine(ConDatos[Data]), "month_start", each try #date([pickup_year], [pickup_month], 1) otherwise null, type date)
				in
				    Combinado

	annotation PBI_ResultType = Table
