table Fact_DemandaDiaria

	measure 'D1 Viajes Totales' = SUM(Fact_DemandaDiaria[Cantidad de viajes])
		formatString: #,0
		displayFolder: Medidas

	measure 'D1 Ingresos Totales' = SUM(Fact_DemandaDiaria[Ingresos totales])
		formatString: $#,0.00
		displayFolder: Medidas

	measure 'D1 Ingreso por Viaje' = DIVIDE([D1 Ingresos Totales], [D1 Viajes Totales])
		formatString: $#,0.00
		displayFolder: Medidas

	measure 'D1 Distancia Promedio' = DIVIDE(SUM(Fact_DemandaDiaria[Distancia total en millas]), [D1 Viajes Totales])
		formatString: 0.00 "mi"
		displayFolder: Medidas

	column 'Fecha de recogida'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: pickup_date

	column 'Mes de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_month

	column 'Día de la semana'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_day_of_week

	column 'Servicio'
		dataType: string
		summarizeBy: none
		sourceColumn: service

	column 'ID zona de origen'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_location_id

	column 'Distrito de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_borough

	column 'Zona de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_zone

	column 'Tipo de zona de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_service_zone

	column 'Cantidad de viajes'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: trip_count

	column 'Cantidad de pasajeros'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: passenger_total

	column 'Ingresos totales'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: total_revenue

	column 'Ingresos por tarifa'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: fare_revenue

	column 'Ingresos por propinas'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tip_revenue

	column 'Ingresos por peajes'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tolls_revenue

	column 'Distancia total en millas'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: distance_miles

	column 'Duración total en minutos'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: duration_minutes

	column 'Distancia promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_distance

	column 'Duración promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_duration_minutes

	column 'Importe total promedio'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_total_amount

	column 'Viajes nocturnos'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: night_trips

	column 'Viajes en hora punta'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: rush_hour_trips

	column 'Viajes de fin de semana'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: weekend_trips

	column 'Ingreso por viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: revenue_per_trip

	column 'Velocidad promedio en mph'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_speed_mph

	column 'Proporción de propina'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tip_share

	column 'Año de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_year

	partition Fact_DemandaDiaria = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/descriptive_daily_demand"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in Table.AddColumn(t, "pickup_year", each y, Int64.Type)),
				    Combinado = Table.Combine(ConDatos[Data])
				in
				    Combinado

	annotation PBI_ResultType = Table
