table Fact_ClasificacionDemanda

	measure 'D9 Casos Evaluados' = COUNTROWS(Fact_ClasificacionDemanda)
		formatString: #,0
		displayFolder: Medidas

	measure 'D9 Aciertos' = SUMX(Fact_ClasificacionDemanda, IF(Fact_ClasificacionDemanda[Alta demanda real] = Fact_ClasificacionDemanda[Alta demanda predicha], 1, 0))
		formatString: #,0
		displayFolder: Medidas

	measure 'D9 Exactitud Calculada' = DIVIDE([D9 Aciertos], [D9 Casos Evaluados])
		formatString: 0.00%
		displayFolder: Medidas

	measure 'D9 Probabilidad Promedio' = AVERAGE(Fact_ClasificacionDemanda[Probabilidad de alta demanda])
		formatString: 0.00%
		displayFolder: Medidas

	column 'ID interno de zona'
		dataType: string
		summarizeBy: none
		sourceColumn: zone_id

	column 'Fecha de predicción'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: prediction_date

	column 'Viajes reales'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: actual_trips

	column 'Umbral de alta demanda'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: high_demand_threshold

	column 'Alta demanda real'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: actual_high_demand

	column 'Alta demanda predicha'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: predicted_high_demand

	column 'Probabilidad de alta demanda'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: probability_high_demand

	column 'Fecha de corte temporal'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: temporal_cutoff

	column 'Nombre de zona'
		dataType: string
		summarizeBy: none
		sourceColumn: zone_name

	column 'Nombre del modelo'
		dataType: string
		summarizeBy: none
		sourceColumn: model_name

	column 'Conjunto de evaluación'
		dataType: string
		summarizeBy: none
		sourceColumn: dataset_split

	column 'Fecha de recogida'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: pickup_date

	column 'ID zona de origen'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_location_id

	column 'Clase real'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: label

	column 'Clase predicha'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: prediction

	column 'Fecha de generación UTC'
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: generated_at_utc

	partition Fact_ClasificacionDemanda = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/model_classification_demand"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in t),
				    Combinado = Table.Combine(ConDatos[Data])
				in
				    Combinado

	annotation PBI_ResultType = Table
