table Fact_PerfilHorario

	measure 'D2 Viajes Totales' = SUM(Fact_PerfilHorario[Cantidad de viajes])
		formatString: #,0
		displayFolder: Medidas

	measure 'D2 Duracion Promedio Ponderada' = DIVIDE(SUM(Fact_PerfilHorario[Duración total en minutos]), [D2 Viajes Totales])
		formatString: 0.00 "min"
		displayFolder: Medidas

	measure 'D2 Ingresos Totales' = SUM(Fact_PerfilHorario[Ingresos totales])
		formatString: $#,0.00
		displayFolder: Medidas

	column 'Fecha de recogida'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: pickup_date

	column 'Mes de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_month

	column 'Día de la semana'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_day_of_week

	column 'Hora de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_hour

	column 'Servicio'
		dataType: string
		summarizeBy: none
		sourceColumn: service

	column 'ID zona de origen'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_location_id

	column 'Distrito de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_borough

	column 'Zona de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_zone

	column 'Tipo de zona de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_service_zone

	column 'Cantidad de viajes'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: trip_count

	column 'Ingresos totales'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: total_revenue

	column 'Ingresos por propinas'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tip_revenue

	column 'Distancia total en millas'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: distance_miles

	column 'Duración total en minutos'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: duration_minutes

	column 'Distancia promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_distance

	column 'Duración promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_duration_minutes

	column 'Importe total promedio'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_total_amount

	column 'Año de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_year

	partition Fact_PerfilHorario = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/descriptive_hourly_profile"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in Table.AddColumn(t, "pickup_year", each y, Int64.Type)),
				    Combinado = Table.Combine(ConDatos[Data])
				in
				    Combinado

	annotation PBI_ResultType = Table
