table Fact_MatrizConfusion

	measure 'D9 Matriz Casos' = SUM(Fact_MatrizConfusion[Cantidad de casos])
		formatString: #,0
		displayFolder: Medidas

	column 'Clase real'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: actual_label

	column 'Clase predicha'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: predicted_label

	column 'Cantidad de casos'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: count

	column 'Nombre del modelo'
		dataType: string
		summarizeBy: none
		sourceColumn: model_name

	column 'Fecha de generación UTC'
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: generated_at_utc

	partition Fact_MatrizConfusion = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/model_classification_confusion"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in t),
				    Combinado = Table.Combine(ConDatos[Data])
				in
				    Combinado

	annotation PBI_ResultType = Table
