table Fact_PerfilesSegmentacion

	column 'ID de segmento'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: segment_id

	column 'Cantidad de zonas'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: zone_count

	column 'Viajes totales'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: total_trips

	column 'Promedio de viajes diarios'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_avg_daily_trips

	column 'Variabilidad promedio de la demanda'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_demand_stddev

	column 'Días activos promedio'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_active_days

	column 'Promedio de tarifa'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_avg_fare_amount

	column 'Promedio de distancia'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_avg_trip_distance

	column 'Promedio de duración'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_avg_duration_minutes

	column 'Ingreso total promedio'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_total_revenue

	column 'Nivel de demanda'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: demand_rank

	column 'Perfil del segmento'
		dataType: string
		summarizeBy: none
		sourceColumn: segment_label

	column 'Participación de viajes'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: trip_share

	column 'Nombre del modelo'
		dataType: string
		summarizeBy: none
		sourceColumn: model_name

	column 'Fecha de generación UTC'
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: generated_at_utc

	partition Fact_PerfilesSegmentacion = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/model_segmentation_profiles"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in t),
				    Combinado = Table.Combine(ConDatos[Data])
				in
				    Combinado

	annotation PBI_ResultType = Table
