table Fact_AnomaliasDiarias

	measure 'D4 Anomalias Detectadas' = CALCULATE(COUNTROWS(Fact_AnomaliasDiarias), Fact_AnomaliasDiarias[Es anomalía] = TRUE())
		formatString: #,0
		displayFolder: Medidas

	measure 'D4 Porcentaje Anomalias' = DIVIDE([D4 Anomalias Detectadas], COUNTROWS(Fact_AnomaliasDiarias))
		formatString: 0.00%
		displayFolder: Medidas

	measure 'D4 Puntaje Z Máximo' = MAXX(Fact_AnomaliasDiarias, ABS(Fact_AnomaliasDiarias[Puntaje Z de demanda]))
		formatString: 0.00
		displayFolder: Medidas

	column 'Fecha de recogida'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: pickup_date

	column 'Día de la semana'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_day_of_week

	column 'Servicio'
		dataType: string
		summarizeBy: none
		sourceColumn: service

	column 'ID zona de origen'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_location_id

	column 'Distrito de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_borough

	column 'Zona de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_zone

	column 'Tipo de zona de origen'
		dataType: string
		summarizeBy: none
		sourceColumn: pickup_service_zone

	column 'Cantidad de viajes'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: trip_count

	column 'Cantidad de pasajeros'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: passenger_total

	column 'Ingresos totales'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: total_revenue

	column 'Ingresos por tarifa'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: fare_revenue

	column 'Ingresos por propinas'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tip_revenue

	column 'Ingresos por peajes'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tolls_revenue

	column 'Distancia total en millas'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: distance_miles

	column 'Duración total en minutos'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: duration_minutes

	column 'Distancia promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_distance

	column 'Duración promedio del viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_trip_duration_minutes

	column 'Importe total promedio'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_total_amount

	column 'Viajes nocturnos'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: night_trips

	column 'Viajes en hora punta'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: rush_hour_trips

	column 'Viajes de fin de semana'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: weekend_trips

	column 'Ingreso por viaje'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: revenue_per_trip

	column 'Velocidad promedio en mph'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: avg_speed_mph

	column 'Proporción de propina'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: tip_share

	column 'Promedio base de viajes'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: baseline_avg_trips

	column 'Desviación base de viajes'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: baseline_stddev_trips

	column 'Ingreso promedio base'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: baseline_avg_revenue

	column 'Desviación base de ingresos'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: baseline_stddev_revenue

	column 'Puntaje Z de demanda'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: demand_zscore

	column 'Puntaje Z de ingresos'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: revenue_zscore

	column 'Es anomalía'
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_anomaly

	column 'Dirección de la anomalía'
		dataType: string
		summarizeBy: none
		sourceColumn: anomaly_direction

	column 'Año de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_year

	column 'Mes de recogida'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: pickup_month

	partition Fact_AnomaliasDiarias = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/diagnostic_daily_anomalies"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in Table.AddColumn(Table.AddColumn(t, "pickup_year", each y, Int64.Type), "pickup_month", each m, Int64.Type)),
				    Combinado = Table.Combine(ConDatos[Data])
				in
				    Combinado

	annotation PBI_ResultType = Table
