table Fact_PronosticoDemanda

	measure 'D7 Viajes Pronosticados' = SUM(Fact_PronosticoDemanda[Viajes pronosticados])
		formatString: #,0
		displayFolder: Medidas

	measure 'D7 Limite Inferior 95' = SUM(Fact_PronosticoDemanda[Límite inferior al 95 %])
		formatString: #,0
		displayFolder: Medidas

	measure 'D7 Limite Superior 95' = SUM(Fact_PronosticoDemanda[Límite superior al 95 %])
		formatString: #,0
		displayFolder: Medidas

	column 'Fecha pronosticada'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: forecast_date

	column 'Tipo de servicio'
		dataType: string
		summarizeBy: none
		sourceColumn: service_type

	column 'Viajes pronosticados'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: forecast_trips

	column 'Día del horizonte'
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: horizon_day

	column 'Límite inferior al 95 %'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: forecast_lower_95

	column 'Límite superior al 95 %'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: forecast_upper_95

	column 'Nombre del modelo'
		dataType: string
		summarizeBy: none
		sourceColumn: model_name

	column 'Fecha de recogida'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: pickup_date

	column 'Servicio'
		dataType: string
		summarizeBy: none
		sourceColumn: service

	column 'Fecha de la serie'
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: ds

	column 'Predicción del modelo'
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: yhat

	column 'Fecha de generación UTC'
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: generated_at_utc

	partition Fact_PronosticoDemanda = m
		mode: import
		source =
				let
				    Origen = Folder.Files("C:/Users/Pieers/dev/bigdata-final/data/gold/model_timeseries_daily"),
				    Parquet = Table.SelectRows(Origen, each [Extension] = ".parquet"),
				    ConDatos = Table.AddColumn(Parquet, "Data", each let p=Text.Replace([Folder Path], "\\", "/"), y=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_year="), "/")) otherwise null, m=try Number.FromText(Text.BeforeDelimiter(Text.AfterDelimiter(p, "pickup_month="), "/")) otherwise null, t=Parquet.Document([Content]) in t),
				    Combinado = Table.Combine(ConDatos[Data])
				in
				    Combinado

	annotation PBI_ResultType = Table
